{ config, lib, pkgs, ... }:

{
  wayland.windowManager.hyprland.settings = {
    bind = [
      "$mainMod, B, exec, firefox"
      "SUPER_SHIFT, B, exec, brave --password-store=basic --incognito"
      "$mainMod, P, exec, bitwarden-desktop"
      ", PRINT, exec, hyprshot -m region"
      "$mainMod, S, exec, hyprshot -m output -m eDP-1"
      "SUPER_SHIFT, S, exec, hyprshot -m window"
      "$mainMod, E, exec, thunar"
      "$mainMod, ESCAPE, exec, wlogout"
      "$mainMod, M, exec, spotify"
      "$mainMod, Return, exec, kitty"
      "$mainMod, Q, killactive,"
      "$mainMod, R, exec, rofi -show drun"
      "SUPER_SHIFT, P, exec, killall waybar; waybar"
      "SUPER_SHIFT, W, exec, bash ~/.dotfiles/Bash-Scripts/Wallpaper.sh"
      ", F12, exec, pkill waybar || waybar"
      ", F1, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0%"
      ", F2, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      ", F3, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ", F4, exec, brightnessctl set 1%-"
      ", F5, exec, brightnessctl set 1%+"
      ", F6, exec, brightnessctl set 1%"
      ", F7, exec, brightnessctl set 100%"
      "$mainMod SHIFT, L, resizeactive, 100 0"
      "$mainMod SHIFT, H, resizeactive, -100 0"
      "$mainMod SHIFT, K, resizeactive, 0 -100"
      "$mainMod SHIFT, J, resizeactive, 0 100"
      "$mainMod, J, movefocus, d"
      "$mainMod, K, movefocus, u"
      "$mainMod, L, movefocus, r"
      "$mainMod, H, movefocus, l"
      "$mainMod, TAB, swapsplit"
      "$mainMod, F, fullscreen, 0"
      "$mainMod, T, togglesplit"
      "$mainMod, A, exec, hyprctl dispatch workspaceopt allfloat"
      "SUPER_SHIFT, F, togglefloating,"
      "$mainMod, 1, workspace, 1"
      "$mainMod, 2, workspace, 2"
      "$mainMod, 3, workspace, 3"
      "$mainMod, 4, workspace, 4"
      "$mainMod, 5, workspace, 5"
      "$mainMod, 6, workspace, 6"
      "$mainMod, 7, workspace, 7"
      "$mainMod, 8, workspace, 8"
      "$mainMod, 9, workspace, 9"
      "$mainMod, 0, workspace, 10"
      "$mainMod SHIFT, 1, movetoworkspace, 1"
      "$mainMod SHIFT, 2, movetoworkspace, 2"
      "$mainMod SHIFT, 3, movetoworkspace, 3"
      "$mainMod SHIFT, 4, movetoworkspace, 4"
      "$mainMod SHIFT, 5, movetoworkspace, 5"
      "$mainMod SHIFT, 6, movetoworkspace, 6"
      "$mainMod SHIFT, 7, movetoworkspace, 7"
      "$mainMod SHIFT, 8, movetoworkspace, 8"
      "$mainMod SHIFT, 9, movetoworkspace, 9"
      "$mainMod SHIFT, 0, movetoworkspace, 10"
      "$mainMod, mouse_down, workspace, e+1"
      "$mainMod, mouse_up, workspace, e-1"
    ];
    bindm = [
      "$mainMod, mouse:272, movewindow"
      "$mainMod, mouse:273, resizewindow"
    ];
  };
}
