{pkgs, ...}: {
  wayland.windowManager.hyprland.settings = {
    bind = [
      "$mainMod, B, exec, ${pkgs.firefox}/bin/firefox"
      "SUPER_SHIFT, B, exec, ${pkgs.librewolf}/bin/librewolf --private-window"
      ", PRINT, exec, ${pkgs.hyprshot}/bin/hyprshot -m region"
      "$mainMod, S, exec, ${pkgs.hyprshot}/bin/hyprshot -m output -m active"
      "$mainMod, ESCAPE, exec, ${pkgs.wlogout}/bin/wlogout"
      "SUPER_SHIFT, ESCAPE, exec, ${pkgs.hyprlock}/bin/hyprlock"
      "$mainMod, M, exec, spotify" # Do not run direct binary for spotify because of spicetify
      "$mainMod SHIFT, M, exec, flatpak run me.proton.Mail" # Do not run direct binary for proton mail since it is flatpak
      "$mainMod, P, exec, flatpak run me.proton.Pass"
      "$mainMod, A, exec, ${pkgs.pavucontrol}/bin/pavucontrol"
      "$mainMod, Return, exec, ${pkgs.wezterm}/bin/wezterm"
      "$mainMod SHIFT, Return, exec, ${pkgs.kitty}/bin/kitty"
      "$mainMod, Q, killactive,"
      "$mainMod, R, exec, ${pkgs.rofi-wayland}/bin/rofi -show drun"
      "$mainMod, E, exec, ${pkgs.rofi-wayland}/bin/rofi -show filebrowser"
      "$mainMod SHIFT, E, exec, ${pkgs.xfce.thunar}/bin/thunar"
      # "$mainMod, E, exec, ${pkgs.xfce.thunar}/bin/thunar"
      "$mainMod, N, exec, ${pkgs.networkmanagerapplet}/bin/nm-connection-editor"
      "$mainMod SHIFT, N, exec, ${pkgs.blueman}/bin/blueman-manager"
      "$mainMod, D, exec, ${pkgs.vesktop}/bin/vesktop"
      "$mainMod SHIFT, O, exec, ${pkgs.rclone}/bin/rclone --vfs-cache-mode writes mount OneDrive: ~/OneDrive/ &"
      ", F12, exec, pkill waybar || ${pkgs.waybar}/bin/waybar"
      ", F1, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0%"
      ", F2, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      ", F3, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ", F4, exec, ${pkgs.brightnessctl}/bin/brightnessctl set 1%-"
      ", F5, exec, ${pkgs.brightnessctl}/bin/brightnessctl set 1%+"
      ", F6, exec, ${pkgs.brightnessctl}/bin/brightnessctl set 1%"
      ", F7, exec, ${pkgs.brightnessctl}/bin/brightnessctl set 100%"
      "$mainMod, right, resizeactive, 100 0"
      "$mainMod, left, resizeactive, -100 0"
      "$mainMod, down, resizeactive, 0 -100"
      "$mainMod, up, resizeactive, 0 100"
      "$mainMod, J, movefocus, d"
      "$mainMod, K, movefocus, u"
      "$mainMod, L, movefocus, r"
      "$mainMod, H, movefocus, l"
      "$mainMod SHIFT, L, movetoworkspace, e+1"
      "$mainMod SHIFT, H, movetoworkspace, e-1"
      "$mainMod, TAB, swapsplit"
      "$mainMod, F, fullscreen, 0"
      "$mainMod, T, togglesplit"
      # "$mainMod, A, exec, hyprctl dispatch workspaceopt allfloat"
      "SUPER_SHIFT, F, exec, hyprctl dispatch togglefloating && if hyprctl activewindow | grep -q 'floating: 1'; then hyprctl dispatch resizeactive exact 800 600 && hyprctl dispatch centerwindow; fi"
      "$mainMod, 1, workspace, 1"
      "$mainMod, 2, workspace, 2"
      "$mainMod, 3, workspace, 3"
      "$mainMod, 4, workspace, 4"
      "$mainMod, 5, workspace, 5"
      "$mainMod, 6, workspace, 6"
      "$mainMod, 7, workspace, 7"
      "$mainMod, 8, workspace, 8"
      "$mainMod, 9, workspace, 9"
      "$mainMod, 0, workspace, 10"
      "$mainMod SHIFT, 1, movetoworkspace, 1"
      "$mainMod SHIFT, 2, movetoworkspace, 2"
      "$mainMod SHIFT, 3, movetoworkspace, 3"
      "$mainMod SHIFT, 4, movetoworkspace, 4"
      "$mainMod SHIFT, 5, movetoworkspace, 5"
      "$mainMod SHIFT, 6, movetoworkspace, 6"
      "$mainMod SHIFT, 7, movetoworkspace, 7"
      "$mainMod SHIFT, 8, movetoworkspace, 8"
      "$mainMod SHIFT, 9, movetoworkspace, 9"
      "$mainMod SHIFT, 0, movetoworkspace, 10"
      "$mainMod, mouse_down, workspace, e+1"
      "$mainMod, mouse_up, workspace, e-1"
    ];
    bindm = [
      "$mainMod, mouse:272, movewindow"
      "$mainMod, mouse:273, resizewindow"
    ];
  };
}
