{pkgs, ...}: {
  wayland.windowManager.hyprland.settings = {
    binde = [
      "$mainMod, TAB, exec, next_workspace"
      "$mainMod SHIFT, TAB, exec, previous_workspace"
      ", F2, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      ", F3, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ", F4, exec, ${pkgs.brightnessctl}/bin/brightnessctl set 1%-"
      ", F5, exec, ${pkgs.brightnessctl}/bin/brightnessctl set 1%+"
      "$mainMod, right, resizeactive, 100 0"
      "$mainMod, left, resizeactive, -100 0"
      "$mainMod, down, resizeactive, 0 -100"
      "$mainMod, up, resizeactive, 0 100"
      "$mainMod, J, movefocus, d"
      "$mainMod, K, movefocus, u"
      "$mainMod, L, movefocus, r"
      "$mainMod, H, movefocus, l"
    ];
    bind = [
      "$mainMod, B, exec, firefox"
      "$mainMod, V, exec, protonvpn"
      "SUPER_SHIFT, B, exec, brave --incognito"
      "$mainMod, A, exec, brave --app=https://chatgpt.com"
      "$mainMod, Y, exec, brave --app=https://youtube.com"
      ", PRINT, exec, ${pkgs.hyprshot}/bin/hyprshot -m region"
      "$mainMod, S, exec, ${pkgs.hyprshot}/bin/hyprshot -m output -m active"
      "$mainMod SHIFT, S, exec, ${pkgs.hyprshot}/bin/hyprshot -m region"
      "$mainMod, ESCAPE, exec, wlogout"
      "SUPER_SHIFT, ESCAPE, exec, hyprlock"
      "$mainMod, M, exec, proton-mail"
      "$mainMod, P, exec, ${pkgs.proton-pass}/bin/proton-pass"
      "$mainMod, Return, exec, st"
      "$mainMod SHIFT, Return, exec, kitty"
      "$mainMod, Q, killactive,"
      "$mainMod, R, exec, rofi -show drun"
      ''$mainMod, O, exec, zathura "$(find "$HOME/Documents/Books" -maxdepth 2 -type f | rofi -dmenu -i -p 'Open book:')"''
      "$mainMod SHIFT, R, exec, rofi -show ssh"
      "$mainMod, E, exec, rofi -show filebrowser"
      "$mainMod SHIFT, E, exec, thunar"
      "$mainMod, N, exec, ${pkgs.networkmanagerapplet}/bin/nm-connection-editor"
      "$mainMod SHIFT, N, exec, ${pkgs.blueman}/bin/blueman-manager"
      "$mainMod SHIFT, O, exec, ${pkgs.rclone}/bin/rclone --vfs-cache-mode writes mount OneDrive: ~/OneDrive/ &"
      ", F12, exec, pkill waybar || waybar"
      ", F1, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0%"
      ", F6, exec, ${pkgs.brightnessctl}/bin/brightnessctl set 1%"
      ", F7, exec, ${pkgs.brightnessctl}/bin/brightnessctl set 100%"
      "$mainMod, T, swapsplit"
      "$mainMod, F, fullscreen, 0"
      "$mainMod SHIFT, T, togglesplit"
      "SUPER_SHIFT, F, exec, hyprctl dispatch togglefloating && if hyprctl activewindow | grep -q 'floating: 1'; then hyprctl dispatch resizeactive exact 800 600 && hyprctl dispatch centerwindow; fi"
      "$mainMod, 1, workspace, 1"
      "$mainMod, 2, workspace, 2"
      "$mainMod, 3, workspace, 3"
      "$mainMod, 4, workspace, 4"
      "$mainMod, 5, workspace, 5"
      "$mainMod, 6, workspace, 6"
      "$mainMod, 7, workspace, 7"
      "$mainMod, 8, workspace, 8"
      "$mainMod, 9, workspace, 9"
      "$mainMod, 0, workspace, 10"
      "$mainMod SHIFT, 1, movetoworkspace, 1"
      "$mainMod SHIFT, 2, movetoworkspace, 2"
      "$mainMod SHIFT, 3, movetoworkspace, 3"
      "$mainMod SHIFT, 4, movetoworkspace, 4"
      "$mainMod SHIFT, 5, movetoworkspace, 5"
      "$mainMod SHIFT, 6, movetoworkspace, 6"
      "$mainMod SHIFT, 7, movetoworkspace, 7"
      "$mainMod SHIFT, 8, movetoworkspace, 8"
      "$mainMod SHIFT, 9, movetoworkspace, 9"
      "$mainMod SHIFT, 0, movetoworkspace, 10"
      "$mainMod, mouse_down, workspace, e+1"
      "$mainMod, mouse_up, workspace, e-1"
    ];
    bindm = [
      "$mainMod, mouse:272, movewindow"
      "$mainMod, mouse:273, resizewindow"
    ];
  };
}
