{pkgs, ...}: {
  environment = {
    shells = with pkgs; [bash];
    sessionVariables = {
      nixos_ozone_wl = "1";
    };
    systemPackages = with pkgs; [
      vim
      wget
      hyprland
      xfce.thunar
      hyprshot
      waybar
      kitty
      swaynotificationcenter
      wl-clipboard
      networkmanagerapplet
      firefox
      zathura
      fastfetch
      rclone
      yazi
      starship
      git
      atuin
      neovim
      lua
      fd
      python3
      cmake
      gnumake
      unzip
      nodejs_20.out
      fzf
      imagemagick
      gcc
      wlogout
      bitwarden-desktop
      brightnessctl
      R
      blueman
      postgresql_17
      postgresql17Packages.postgis
      bibata-cursors
      papirus-icon-theme
      openvpn
      btop
      nix-ld
      glibc
      htop
      libnotify
      pavucontrol
      greetd.tuigreet
      spotify
      spicetify-cli
      obs-studio
      onefetch
      timg
      flatpak
      plocate
      vlc
      speedtest-cli
      base16-schemes
      wofi
      yq
      zellij
      librewolf
      microfetch
      lsd
      gimp
      ripgrep
      ltex-ls
      vesktop
      brave
      entr
      pandoc
      texliveFull
    ];
  };
}
